---
title: ""
output: html_document
---

<br>
<br>
<br>

<p style="font-size:24px"><b>Peer-reviewed scientific journals</b></p>

<p class="hangingindent">Zuniga-Montanez, C., Krott, A., <b>Aussems, S.</b>, & Kita, S. (2020). Beyond the shape of things: Infants can be taught to generalise nouns by function</a>. <i>Psychological Science</i>. </p>

<p class="hangingindent"><b>Aussems, S.</b>, & Kita, S. (2020). <a href="https://srcd.onlinelibrary.wiley.com/doi/full/10.1111/cdev.13392">Seeing iconic gesture promotes first- and second-order verb generalization in preschoolers</a>. <i>Child Development</i>. doi: 10.1111/cdev.13392</p>

<p class="hangingindent"><b>Aussems, S.</b> (2019). <a href="https://www.tandfonline.com/doi/abs/10.1080/10489223.2019.1624759">How seeing iconic gestures facilitates action event memory and verb learning in 3-year-old children</a>. <i>Language Acquisition, 27</i>(1), 68-70. doi: 10.1080/10489223.2019.1624759</p>

<p class="hangingindent"><b>Aussems, S.</b>, & Vogt., P. (2018). <a href="https://ieeexplore.ieee.org/document/8464247/authors#authors">Adults use distributional statistics for word learning in a conservative way</a>. <i>IEEE Transactions on Cognitive and Developmental Systems, 12</i>(2), 232-242. doi: 10.1109/TCDS.2018.2870161</p>

<p class="hangingindent"><b>Aussems, S.</b>, & Kita, S. (2017). <a href="https://srcd.onlinelibrary.wiley.com/doi/abs/10.1111/cdev.12988">Seeing iconic gestures with action events facilitates children's memory of these events</a>. <i>Child Development, 90</i>(4), 1123-1137. doi: 10.1111/cdev.12988</p>

<p class="hangingindent"><b>Aussems, S.</b>, Kwok, N., & Kita, S. (2017). <a href="https://link.springer.com/article/10.3758/s13428-017-0942-2">GestuRe and ACtion Exemplar (GRACE) video database: Stimuli for research on manners of human locomotion and iconic gestures</a>. <i>Behavior Research Methods, 50</i>(3), 1270-1284. doi: 10.3758/s13428-017-0942-2</p>

<p class="hangingindent">Vogt, P., Mastin, J. D., & <b>Aussems, S.</b> (2015). <a href="https://www.hindawi.com/journals/cdr/2015/189195/">Early vocabulary development in rural and urban Mozambique</a>. <i>Child Development Research</i>, vol. 2015, Article ID 189195, 15 pages. doi: 10.1155/2015/189195</p>

<p style="font-size:24px"><b>Peer-reviewed conference proceedings</b></p>

<p class="hangingindent"><b>Aussems, S.</b>, & Kita, S. (2019). Seeing iconic gesture promotes first- and second-order verb generalization in pre-schoolers. <i>In proceedings of the Child Language Symposium (CLShef19)</i>, University of Sheffield, UK.</p>

<p class="hangingindent"><b>Aussems, S.</b>, & Kita, S. (2019). Seeing iconic gesture promotes second-order verb generalization in pre-schoolers. <i>In proceedings of the Budapest CEU Conference on Cognitive Development (BCCCD)</i>, Central European University, Budapest, Hungary.</p>

<p class="hangingindent"><b>Aussems, S.</b>, & Kita, S. (2018). Seeing iconic gestures promotes lasting word-category knowledge about verbs in children. <i>In proceedings the 8th conference of the International Society of Gesture Studies (ISGS8)</i>, Cape Town, South Africa.</p>

<p class="hangingindent">Kita, S., <b>Aussems, S.</b>, & Mumford, K. (2018). Seeing iconic gestures helps three-year-olds learn verbs. <i>In proceedings of the 8th conference of the International Society of Gesture Studies (ISGS8)</i>, Cape Town, South Africa.</p>

<p class="hangingindent"><b>Aussems, S.</b>, & Kita, S. Who did what? How iconic gestures help young children to encode action events. <i>In proceedings of the “Iconicity Focus Group Workshop”</i>, Centre for Language Studies & Max Planck Institute for Psycholinguistics Workshop, Nijmegen, The Netherlands.</p>

<p class="hangingindent"><b>Aussems, S.</b>, Mumford, K., & Kita, S. (2017). Prior experience with actions that were highlighted by iconic gestures facilitates verb learning in three-year-olds. <i>In proceedings of the 14th International Congress for the Study of Child Language (IASCL)</i>, Université Lyon, France.</p>

<p class="hangingindent"><b>Aussems, S.</b>, Mumford, K. H., & Kita, S. (2017). Seeing iconic gestures helps 3-year-olds link multiple exemplars for verb learning. <i>In proceedings of the International Conference on Gesture and Multimodality (iGesto'17)</i>, University of Porto, Portugal.<p>

<p class="hangingindent"><b>Aussems, S.</b>, & Kita, S. (2016). How iconic hand gestures can change children's memory representation of action events. <i>In proceedings of the 7th conference of the International Society of Gesture Studies (ISGS7)</i>, Paris, France.</p>

<p class="hangingindent"><b>Aussems, S.</b>, Chu, M., Kita, S., & van Zaanen, M. (2015). Applying pattern-based classification to sequences of gestures. <i>In Noelle, D. C., Dale, R., Warlaumont, A. S., Yoshimi, J., Matlock, T., Jennings, C. D., & Maglio, P. P. (Eds.), proceedings of the 37th annual meeting of the Cognitive Science Society</i> (pp. 124-129). Austin, TX: Cognitive Science Society.</p>

<p class="hangingindent"><b>Aussems, S.</b>, & Vogt, P. (2015). Adults track multiple hypotheses simultaneously during word learning. <i>In Noelle, D. C., Dale, R., Warlaumont, A. S., Yoshimi, J., Matlock, T., Jennings, C. D., & Maglio, P. P. (Eds.), proceedings of the 37th annual meeting of the Cognitive Science Society</i>(pp. 118-123). Austin, TX: Cognitive Science Society.</p>

<p class="hangingindent">van Zaanen, M., van Huyssteen, G., <b>Aussems, S.</b>, Emmery, C., & Eiselen, R. (2014). The development of Dutch and Afrikaans language resources for compound boundary analysis. <i>In N. Calzolari et al. (Eds.), proceedings of the 9th international conference on Language Resources and Evaluation (LREC)</i> (pp. 1056-1062). Reykjavik, Iceland.</p>

<p class="hangingindent"><b>Aussems, S.</b>, & Vogt, P. (2013). Exploring cross-situational learning and mutual exclusivity. <i> In M. Knauff, M. Pauen, N. Sebanz, & I. Wachsmuth (Eds.), proceedings of the 35th annual conference of the Cognitive Science Society</i> (p. 3874). Austin, TX: Cognitive Science Society.</p>

<p class="hangingindent"><b>Aussems, S.</b>, Goris, B., Lichtenberg, V., van Noord, N., Smetsers, R., & van Zaanen, M. (2013). Unsupervised identification of compounds. <i>In proceedings of the 22nd annual Belgian-Dutch conference on machine learning (BENELEARN)</i> (pp. 18-25). Nijmegen, The Netherlands.</p>

<p class="hangingindent"><b>Aussems, S.</b>, Bruys, S., Goris, B., Lichtenberg, V., van Noord, N., Smetsers, R., & van Zaanen, M. (2013). Automatically identifying compounds. <i>In book of abstracts of the 23rd meeting of Computational Linguistics in the Netherlands (CLIN)</i> (p. 10). Enschede, The Netherlands.</p>

<p style="font-size:24px"><b>Blog posts</b></p>

Ricketts, J., & <b>Aussems, S.</b> (2020). <a href="https://www.tes.com/news/what-eyfs-teachers-need-know-about-shared-reading">What EYFS teachers need to know about shared reading</a>. <i>TES website</i>.

<b>Aussems, S.</b> (2018). <a href="http://icog.group.shef.ac.uk/what-hand-gestures-tell-us-about-the-evolution-of-language/">What hand gestures tell us about the evolution of language</a>. <i>iCog website</i>.

<p style="font-size:24px"><b>Digital resources</b></p>

<b>Aussems, S.</b>, Kwok, N., & Kita, S. (2017). <a href="http://wrap.warwick.ac.uk/78493/">Digital resource to support : "GestuRe and ACtion Exemplar (GRACE) Video Database: Stimuli for Research on Manners of Human Locomotion and Iconic Gestures"</a>. University of Warwick, Department of Psychology.
